# Generated by Django 4.2.30 on 2026-05-08 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('skill', 'Skill'), ('prompt', 'Prompt'), ('spec', 'Spec'), ('other', 'Other')], default='other', max_length=10)),
                ('path', models.CharField(help_text='Relative path within the project', max_length=512)),
                ('content', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
            options={
                'ordering': ['asset_type', 'name'],
                'unique_together': {('project', 'path')},
            },
        ),
    ]
