# Generated by Django 4.2.30 on 2026-05-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Other Asset',
                'verbose_name_plural': 'Other Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='PromptAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='SkillAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='SpecAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Spec',
                'verbose_name_plural': 'Specs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
    ]
