# Generated by Django 4.2.30 on 2026-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_proxy_asset_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('skill', 'Skill'), ('agent', 'Agent'), ('prompt', 'Prompt'), ('spec', 'Spec'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
