# Generated by Django 4.2.30 on 2026-05-10 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('external_id', models.CharField(blank=True, default='', help_text='Optional session id from MCP/client (e.g. conversation id).', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('observation', 'Observation'), ('recommendation', 'Recommendation'), ('decision', 'Decision'), ('architecture', 'Architecture'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='memory.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['project', 'user', '-last_activity_at'], name='memory_sess_project_9c6ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['external_id'], name='memory_sess_externa_bbb44e_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['session', 'created_at'], name='memory_memo_session_4c66f7_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['tag', 'created_at'], name='memory_memo_tag_ce83fe_idx'),
        ),
    ]
